- key:               tsla-testnet
  name:              Muskcoin Testnet
  client:            muskcoin                             # API client name.
  server:            http://user:password@127.0.0.1:2332 # Public Muskcoin node endpoint.
  height:            4768                                # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         http://explorer.beat-reality.com:3001/address/#{address}
    transaction:     http://explorer.beat-reality.com:3001/tx/#{txid}
  status:            active
